apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: blue-wristband
  name: blue-wristband
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox:1.37.0
    name: blue-wristband
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - effect: NoSchedule
    key: wristband
    operator: Equal
    value: blue
status: {}
